### ISSUE TITLE
Use Material Design?

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/reservation-web#8]
Angular Material could replace Bootstrap. It also provides date- and time-pickers (#6).

https://material.angularjs.org/latest/getting-started

**Comment by rnestler** [comment]
Why was this closed? :wink:

**Comment by dbrgn** [comment]
Since I started rewriting this in Svelte (see https://github.com/coredump-ch/reservation-web/tree/svelte) where we can't use Angular Material. Also, I think the UI is fine.
